name: cktap_transport_nfc_manager
description: An implementation of the cktap_transport package using the nfc_manager plugin
version: 0.1.1
license: MIT
repository: https://github.com/PeteClubSeven/cktap-transport-nfc-manager
funding:
  - https://app.mash.com/e/peteclubseven
platforms:
  android:
  ios:

environment:
  sdk: '>=2.19.6 <4.0.0'
  flutter: ">=3.7.12"

dependencies:
  cktap_transport: ^0.1.0
  flutter:
    sdk: flutter
  nfc_manager: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
